// app/layout.tsx

import { Geist, Geist_Mono } from 'next/font/google';
import { ClientWrapper } from '@/components/ClientWrapper';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/footer';
import { ThemeProvider } from '@/components/theme-provider';

// Setup the fonts
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
        <Navbar />
        {/* Wrap with ClientWrapper for Client Components */}
        <ClientWrapper>{children}</ClientWrapper>
      </ThemeProvider>

      </body>
    </html>
  );
}
